# Accordion type
accordion_type: iconised # change the accordion type here. 
# Available values
# 1. "deafult" for default design without icons.
# 2. "iconised" for accordion with icons.

# Alert
alert:
  design: default # Change alert design here.
  type: dismissible # Change alert type here.
  usage: warning
# Available values
# 1. Alert Design
# 1.a. "default" for default alert design.
# 1.b. "inset_shadow" for inner shadowed alert design
# 2. Alert Type
# 2.a. "default" for default type.
# 2.b. "dismissible" for dismissible alert design.
# 2.c. "content" for centented alert design.

# Author Card
authorcard_design: curved-minimal

# Counter Design
counter_design: boxed-inset-box